from __future__ import annotations
from typing import TYPE_CHECKING
from .base import BaseFormatter

if TYPE_CHECKING:
    from ..generator import PatternModel

class MarkdownFormatter(BaseFormatter):
    def format(self, model: PatternModel) -> str:
        class_label = "Positive" if model.is_positive else "Negative"
        num_features = len(model.alpha_obj) - 1
        
        md = f"## Alpha-Object {model.alpha_idx} ({class_label} Class)\n\n"
        
        # 1. Feature Constraint Table
        md += "### Feature Constraints\n"
        md += "The following table defines the constraints imposed on the decision variables by the selected Alpha-Object:\n\n"
        md += "| Feature | Value ($x_{\\alpha, j}$) | Constraint |\n"
        md += "|:---:|:---:|:---:|\n"
        for j in range(num_features):
            val = model.alpha_obj[j]
            md += f"| X{j+1} | {val:.2f} | $a_{j+1} \\le {val:.2f} \\le b_{j+1}$ |\n"
        md += "\n"
        
        # 2. Objective in LaTeX
        md += "### Objective Function\n"
        md += "Maximize the total coverage of the target class $S^\\pm$:\n\n"
        
        feature_terms_latex = " \\land ".join([f"x_{{i{j+1}}} \\in [a_{j+1}, b_{j+1}]" for j in range(num_features)])
        md += f"$$\\max Z = \\sum_{{i \\in S^\\pm}} \\mathbb{{I}}({feature_terms_latex})$$\n\n"
        
        md += "Explicit objective for the current dataset:\n"
        terms = []
        for i in model.target_set:
            point_terms = " \\land ".join([f"{model.data[i][j]:.2f} \\in [a_{j+1}, b_{j+1}]" for j in range(num_features)])
            terms.append(f"\\mathbb{{I}}({point_terms})")
        
        md += "$$Z = " + " + ".join(terms) + "$$\n\n"
        
        # 3. Constraints in LaTeX
        md += "### Negative Constraints\n"
        md += "Ensure that no objects from the opposite class $S^\\mp$ are covered by the pattern:\n\n"
        md += f"$$\\forall i \\in S^\\mp, \\quad \\mathbb{{I}}({feature_terms_latex}) = 0$$\n\n"
        
        md += "System of equations for negative objects:\n"
        for i in model.opposite_set:
            point_terms = " \\land ".join([f"{model.data[i][j]:.2f} \\in [a_{j+1}, b_{j+1}]" for j in range(num_features)])
            md += f"- $$\\mathbb{{I}}({point_terms}) = 0$$\n"
        
        return md

    def get_extension(self) -> str:
        return "md"

    def get_header(self) -> str:
        header = "# Pattern Discovery Optimization Models\n\n"
        header += "Generated by AlphaPattern Optimizer\n\n"
        header += "---\n\n"
        header += "## Mathematical Notation Legend\n"
        header += "The following table defines the mathematical symbols used in the generated optimization models:\n\n"
        header += "| Symbol | Definition |\n"
        header += "|:---:|:---|\n"
        header += "| $Z$ | The objective function representing the total number of covered positive objects. |\n"
        header += "| $\\mathbb{I}(\\dots)$ | The indicator function, returning 1 if the condition is satisfied and 0 otherwise. |\n"
        header += "| $[a_j, b_j]$ | The closed interval representing the pattern boundaries for feature $j$. |\n"
        header += "| $x_{i,j}$ | The measured value of feature $j$ for the $i$-th object in the dataset. |\n"
        header += "| $S^\\pm$ | The set of objects belonging to the same class as the selected alpha-object. |\n"
        header += "| $S^\\mp$ | The set of objects belonging to the class opposite to the selected alpha-object. |\n"
        header += "| $\\land$ | The logical conjunction operator (AND). |\n"
        header += "| $\\alpha$ | The specific reference object used as an anchor for the current optimization model. |\n\n"
        header += "---\n"
        return header

    def get_separator(self) -> str:
        return "\n---\n\n"
